Fix - text renders with default size when size is 0
gentledepp/SVG pull request #24
Opened 2023-02-01 12:13 UTC by Zeljko-Predjeskovic

2023-02-01 13:21 UTC, gentledepp requested changes
Please do not use _magical numbers_ - there must be a different solution to this

2023-02-01 13:21 UTC, gentledepp commented on Svg/Platform/SkiaTextRenderer.cs
> +                    pen.TextSize = txt.FontSize.Value != 0 ? txt.FontSize.Value : 9;
why `9`? Ist that some _magical number_?

2023-02-01 13:21 UTC, gentledepp commented on Svg/Platform/SkiaTextRenderer.cs
> +                    pen.TextSize = txt.FontSize.Value != 0 ? txt.FontSize.Value : 9;
again... ?

2023-02-02 10:37 UTC, gentledepp commented on Svg/Platform/SkiaTextRenderer.cs
> +                    pen.TextSize = txt.FontSize.Value != 0 ? txt.FontSize.Value : pen.TextSize;
cool - where'd you get that from?

2023-02-02 10:37 UTC, gentledepp approved these changes

2023-02-02 13:56 UTC, eszterhorvath approved these changes

2023-02-02 13:57 UTC, eszterhorvath commented on Svg.Editor.Core/Svg.Editor.Core.csproj
> +    <Version>2.4.3.13</Version>
why 13 after 11?

2023-02-04 13:58 UTC, merged