Fix/11384 draw clippath
gentledepp/SVG pull request #42
Opened 2024-03-05 09:23 UTC by Zeljko-Predjeskovic

2024-03-05 09:31 UTC, gentledepp requested changes
Please complete the one test you have.
It would be even better if you could come up with some more.
But one _correct_ test would already be greatly appreciated ;-)

2024-03-05 09:31 UTC, gentledepp commented on Svg.Tests.Win/SvgClipPathTest.cs
> +
Well... as your comments are indicating: There is no **Assert** part here.
So this is technically no test.

Can you please look at the other existing tests or e.g. the planrendering tests?
There we load a bitmap of what _should_ be rendered.
Then we compare the _actually rendered_ bitmap with it and create a "diff bitmap" (i.e. a bitmap with a black dot everywhere the two bitmaps do not match)
Only if they are 90% or even 100% alike, we let the test pass!

```
using var c = TestHelper.ImageCompare(svgBitmap, pngBitmap);


            c.AssertAreSimilar(92f, svgPath);
```

2024-03-06 12:32 UTC, gentledepp commented on Svg.Tests.Win/SvgTextTests.cs
> +            c.AssertAreSimilar(94f, svgPath);
this is worrysome.
You should not have to reduce the similarity once you implemented a feature. This indicates that you have a regression (i.e. you introduced a render bug)

Actually, when implementing stuff, the similarity should rise!

2024-03-06 12:35 UTC, eszterhorvath commented on Svg/Platform/SkiaGraphics.cs
> +                    // TODO LX is this correct?
@gentledepp is this correct? :D

2024-03-06 14:11 UTC, gentledepp approved these changes

2024-03-06 14:14 UTC, merged